### ISSUE TITLE
The default window size is too big on MacOS that it's impossible to access settings panel

### ISSUE THREAD

**Issue by yuyanMC** [yojohanshinwataikei/Arcade-plus#15]
<img width="1440" alt="截屏2024-03-15 01 52 25" src="https://github.com/yojohanshinwataikei/Arcade-plus/assets/60036604/6985be85-e6aa-4f23-96f4-e260e0652e98">
The situation is shown on the image above. The one on the left is 0.4.4 which works well, and the one on the right is 0.5.2 which is broken.
My screen is 2560x1600. The window is about two times bigger than my screen so I can't open the settings panel and adjust the size.
There are two solutions to solve this problem.
1. Make the default window size lower.
2. Put the settings button on the top of the window.

**Comment by yojohanshinwataikei** [comment]
There are two ways to interpret the screen size. The old version use 2560x1600, but the new version use 1280x800@2x(or larger). This means that with the same setting, new version should have 2x window size.

Note that both the old version and the new version use the same setting file. This means that you have a 1920x1080 resolution for both version, but they behaves differently. Also, this is not the default resolution.

As a workaround, you can set resolution to the default 1280x720 in old version, and then close the old version and launch the new version.

I won't revert this change since this works better when you move the window between screens with different dpi.
